# Generated by Django 2.1.5 on 2019-01-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorname',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
